void ambient_suck_wind()
{
  start_ambient_sound();
}
void ambient_drone()
{
  start_ambient_sound();
}
void ambient_flouro_buzz()
{
  start_ambient_sound();
}
void ambient_drip()
{
  start_ambient_sound();
}
void ambient_comp_hum()
{
  start_ambient_sound();
}
void ambient_thunder()
{
  start_ambient_sound();
}
void ambient_light_buzz()
{
  start_ambient_sound();
}
void ambient_swamp1()
{
  start_ambient_sound();
}
void ambient_swamp2()
{
  start_ambient_sound();
}
